#!/bin/bash

set -e

if [[ $# -ne 1 ]] ; then
    echo "Usage: $0 output-base" 1>&2
    exit 1;
fi

output_base=$1

base_log=$output_base-base.log
build1_log=$output_base-1.log
build2_log=$output_base-2.log

base_image=$output_base-base.sif
build1_image=$output_base-1.sif
build2_image=$output_base-2.sif

if [[ ! -f $base_image ]] ; then
    singularity build --fakeroot $base_image base.def > $base_log 2>&1
fi
if [[ ! -f $build1_image ]] ; then
    singularity build --build-arg base=$base_image --fakeroot $build1_image finish-1.def > $build1_log 2>&1
fi
exit
if [[ ! -f $build2_image ]] ; then
    singularity build --build-arg base=$build1_image --fakeroot $build2_image finish-2.def > $build2_log 2>&1
fi
